title: PV system environemental impact
icon: 🌬
project: parasol-project
database: parasol
root_activity: "[parasol] Full PV system"

# List of impacts to consider
# This should refer key tuples of the impact categories.
# You can pick their name (climate_change, etc) as you wish
impacts:
  climate_change: ['EF v3.1', 'climate change', 'global warming potential (GWP100)']
#  particules: ['EF v3.0','particulate matter formation','impact on human health']
#  mineral_depletion: ['EF v3.0','material resources: metals/minerals','abiotic depletion potential (ADP): elements (ultimate reserves)']

# List of function units to consider
functional_units:
    gross_impact: # The name of each functional unit is up to you
        formula: 1
        unit: "-"

    installed_power: # The name of each functional unit is up to you
        formula: Power_plant_capacity # formula can refer to lca_algebraic parameters
        unit: "kW"

    energy: # The name of each functional unit is up to you
        formula: Power_plant_capacity * Normalised_annual_PV_production_kWh_per_kWp * Power_plant_lifetime
        unit: "kWh"

# List of axes to split impacts
# Can be an empty list if no axis is defined in the project.
# See : https://lca-algebraic.readthedocs.io/en/latest/notebooks/example-notebook.html#Split-impacts-along-axis
axes: ["part"]
